# ==============================================
# SENSITIVE DATABASE CONFIGURATION
# ==============================================
# Replace the values according to your local environment.
# DO NOT commit this file to the repository.

spring.datasource.url=jdbc:postgresql://192.168.1.19:5433/planit
spring.datasource.username=admin
spring.datasource.password=4vw21TTfxO21vVGP
spring.datasource.driver-class-name=org.postgresql.Driver